create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  name text not null default 'Você',
  weight numeric,
  height numeric,
  age integer,
  goal text not null default 'lose',
  kcal integer not null default 1850,
  protein integer not null default 160,
  carbs integer not null default 185,
  fats integer not null default 62,
  sugar integer not null default 46,
  updated_at timestamptz not null default now()
);

create table if not exists public.diary_entries (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  entry_date date not null,
  food_id text not null,
  quantity numeric not null default 1,
  created_at timestamptz not null default now()
);

alter table public.profiles enable row level security;
alter table public.diary_entries enable row level security;

drop policy if exists "Users manage their profile" on public.profiles;
drop policy if exists "Users manage their diary" on public.diary_entries;

create policy "Users manage their profile" on public.profiles
  for all using (auth.uid() = id) with check (auth.uid() = id);
create policy "Users manage their diary" on public.diary_entries
  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);